version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=conectapps_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    networks:
      - contectapp_net

  server-api:
    container_name: server-api
    build: .
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=conectapps_db

    ports:
      - "8023:80"
    depends_on:
      - mysql-db
    networks:
      - contectapp_net

networks:
  contectapp_net:
    driver: bridge
